[common]
platform  = espressif32
board     = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
    bogde/HX711 @ ^0.7.5
    links2004/WebSockets @ ^2.4.0

[env:usb]
extends = common

[env:ota]
extends = common
upload_protocol = espota
upload_port     = thrust-gauge.local
upload_flags    = --auth=thrust
