[common]
platform  = espressif32
board     = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem  = littlefs
board_build.partitions  = min_spiffs.csv
lib_deps =
    bogde/HX711 @ ^0.7.5
    https://github.com/me-no-dev/ESPAsyncWebServer.git

[env:usb]
extends = common

[env:ota]
extends = common
upload_protocol = espota
upload_port     = 192.168.68.53
upload_flags    = --auth=thrust
